apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-backend
  namespace: apps
  labels:
    app: python-backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-backend
  template:
    metadata:
      labels:
        app: python-backend
        tier: backend
    spec:
      containers:
        - name: python-backend
          image: python-backend:7e6b289-1786239351
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
